const blockedWords = [
  "TestWord1", "TestWord2",
  "+18",
  "NSFW, nsfw, Nsfw",
  "PORN", "porn", "Porn",
  "THREESOME", "threesome", "Threesome",
  "TRIO", "trio", "Trio",
  "ANAL", "anal", "Anal",
  "FETISH", "fetish", "Fetish",
  "BONDAGE", "bondage", "Bondage",
  "MILF", "milf", "Milf",
  "BDSM", "bdsm", "Bdsm",
  "GANGBANG", "gangbang", "Gangbang",
  "HARDCORE", "hardcore", "Hardcore",
  "LESBIAN", "lesbian", "Lesbian",
  "GAY", "gay", "Gay",
  "INTERRACIAL", "interracial", "Interracial",
  "AMATEUR", "amateur", "Amateur",
  "MATURE", "mature", "Mature",
  "COUPLE", "couple", "Couple",
  "FANTASY", "fantasy", "Fantasy",
  "ROLEPLAY", "roleplay", "Roleplay",
  "ORGASM", "orgasm", "Orgasm",
  "EROTIC", "erotic", "Erotic",
  "EXPLICIT", "explicit", "Explicit",
  "NAKED", "naked", "Naked",
  "NIPPLE", "nipple", "Nipple",
  "BOOBS", "boobs", "Boobs",
  "TITS", "tits", "Tits",
  "PUSSY", "pussy", "Pussy",
  "BITCH", "bitch", "Bitch",
  "PENETRATION", "penetration", "Penetration",
  "SEDUCTION", "seduction", "Seduction",
  "VOYEUR", "voyeur", "Voyeur",
  "EXHIBITIONISM", "exhibitionism", "Exhibitionism",
  "FANTASIES", "fantasies", "Fantasies",
  "TOYS", "toys", "Toys",
  "ORGY", "orgy", "Orgy",
  "SEXY", "sexy", "Sexy",
  "SEX", "sex", "Sex",
  "KINKY", "kinky", "Kinky",
  "LIBIDO", "libido", "Libido",
  "AROUSAL", "arousal", "Arousal",
  "FOREPLAY", "foreplay", "Foreplay",
  "CLIMAX", "climax", "Climax",
];
export { blockedWords };
